name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
   
    - name: Build
      run: dotnet build /p:UseSharedCompilation=false
      
    - name: Perform CodeQL Analysis
      id: CodeQL_analysis
      uses: github/codeql-action/analyze@v1
    
    - name: Publish
      if: ${{ github.event_name =='push' && github.ref == 'refs/heads/main' }}
      run: dotnet msbuild Das.WorkItemSigner.csproj /t:Push
      env:
        NugetApiKey: ${{ secrets.NUGETAPIKEYBYENGOPS }}
